# Generated by Django 4.2.20 on 2025-03-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_day_workout_exercises'),
        ('routines', '0002_routine_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='routines', to='workouts.workout'),
        ),
    ]
