# Generated by Django 4.2.20 on 2025-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_routine_workouts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='workouts',
        ),
        migrations.AddField(
            model_name='routine',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
