# Generated by Django 4.2.19 on 2025-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sets', models.PositiveIntegerField()),
                ('rep_min', models.PositiveIntegerField()),
                ('rep_max', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
