# Generated by Django 4.2.20 on 2025-04-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rep_max',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rep_min',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight_kg',
        ),
    ]
