# Generated by Django 4.2.20 on 2025-03-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_owner'),
        ('workouts', '0002_workout_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='workouts', to='exercises.exercise'),
        ),
    ]
