# Generated by Django 4.2.20 on 2025-04-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_rename_created_routine_created_at_and_more'),
        ('workouts', '0003_workout_day_workout_exercises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workout',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='routines.routine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.PositiveIntegerField(),
        ),
    ]
